#!/bin/sh
set -e

GIT_VERSION=`git describe --tags --always --match v* --dirty`

case $GIT_VERSION in
	v*) VERSION=`echo $GIT_VERSION | cut -c 2-`
	    ;;
	*)  VERSION=$GIT_VERSION
	    ;;
esac

echo building version $VERSION

ant -Dversion="$VERSION" "$@"

